# Generated by Django 3.0.3 on 2020-02-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_auto_20200209_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='isProfessional',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.BooleanField(default=False),
        ),
    ]
