# Generated by Django 3.0.3 on 2020-02-09 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_musclegroup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musclegroup',
            name='user',
        ),
    ]
