# Generated by Django 3.0.3 on 2020-02-10 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0008_remove_musclegroup_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='Feedback',
        ),
    ]
