# Generated by Django 3.0.3 on 2020-02-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0011_auto_20200214_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='frontend/src/images'),
        ),
    ]
