# Generated by Django 3.0.3 on 2020-02-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0012_auto_20200214_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='musclegroups',
            field=models.ManyToManyField(to='quickstart.Musclegroup'),
        ),
    ]
