# Generated by Django 3.0.3 on 2020-02-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0013_exercise_musclegroups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musclesinexercise',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='musclesinexercise',
            name='musclegroup',
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(to='quickstart.Exercise'),
        ),
        migrations.DeleteModel(
            name='ExercisesInWorkout',
        ),
        migrations.DeleteModel(
            name='MusclesInExercise',
        ),
    ]
