# Generated by Django 3.0.3 on 2020-02-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0014_auto_20200215_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='relations',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='frontend/public/images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
