# Generated by Django 3.0.3 on 2020-02-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0015_auto_20200217_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='musclegroups',
            field=models.ManyToManyField(blank=True, null=True, to='quickstart.Musclegroup'),
        ),
        migrations.AlterField(
            model_name='post',
            name='relations',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(blank=True, null=True, to='quickstart.Exercise'),
        ),
    ]
